blog/urls.py
from django.urls import path
from  .views import renderPosts, post_detail

app_name = 'blog'
urlpatterns = [
    path("", renderPosts, name="posts"),
    path("<int:post_id>", post_detail, name ='post_detail')  ,
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import blog

from portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    path('blog/', include('blog.urls'))
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100) 
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(default=datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to="portfolio/images")   
    url = URLField(blank=True)  

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

# Create your views here.
def renderPosts(request):
    posts = Post.objects.all() 
    return render(request,'posts.html',
                  {'posts' : posts})

def post_detail(request, post_id):
    post=get_object_or_404(Post, pk=post_id)
    return render(request,'post_detail.html',
                  {'post' : post})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def home(request):
    projects = Project.objects.all()

    return render(request, 'home.html',{
        'projects' : projects
    } )

blog/templates/post_detail.html
{% extends 'layour.html'%}

{%block content%}
<div class="text-center">

<h2>{{post.title}}</h2>
<h3 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h3>

<img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
<div class="my-4">
    <p>{{post.description|safe}}</p>
</div>

</div>
{%endblock%}

blog/templates/posts.html
{% extends 'layour.html'%}

{%block content%}

<h1> Post</h1>


{% for post in posts %}
<div class="p-3">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
            </div>

            <div class="col-9">
                <h2>{{post.title}}</h2> 
                <!-- para dejar pocos caracteres en la vista -->
                <p>{{post.description|striptags|truncatechars:100 }}</p>
                <p>{{post.date|date:"D d M Y" |upper}}</p>
                
                <a href="{% url 'blog:post_detail' post.id%}" class="btn btn-primary"> {{post.title}}</a>
            </div>
        </div>   
    </div>
</div>
{% endfor %}


{%endblock%}

portfolio/templates/home.html
{% extends 'layour.html'%}

{%block content%}

{% load static %}
<header class="row bg-black">
  <div class="col-md-4 m-auto">
    <img src="{% static 'portfolio/avatar.jpg' %}" alt="" >
  </div>

  <div class="col-md-8 my-auto p-4">
    <h1> I am <strong>Diego HC</strong></h1>
    <h3>I am a python FullStack Developer</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium sapiente modi ipsam, optio error corporis natus! Ad expedita sit, sequi et quod repudiandae nisi iusto fugiat velit blanditiis repellat iste amet corporis architecto. Laboriosam, reprehenderit obcaecati voluptate, illo optio aliquam quaerat, eligendi voluptatibus quas earum quae quasi veniam magni ipsa. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut, quidem. Recusandae necessitatibus, quis officia, saepe amet sit laborum quasi esse expedita nemo porro, rerum cumque odit debitis voluptas vel maxime vitae ullam. Ullam, error tempore modi quibusdam nam deleniti aperiam sapiente ex aspernatur. Exercitationem cupiditate placeat, quae laborum, eos necessitatibus harum recusandae deserunt et ea nisi provident quod accusantium adipisci!
    </p>
    <a class="btn btn-primary btn-lg rounded-0 my-3" href="{% static 'portfolio/cv.pdf' %}" target="_blank">Download CV</a>
  </div>
</header>

<!-- Porfolio Section -->
<div class="row my-4 text-center">
  <h3>My projects</h3>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos fugiat iste expedita veniam repellat minima consequuntur quo natus eum nemo!</p>

{% for project in projects %}
<div class="col-md-4 p-4">
  <div class="card bg-black  card-project">
      <div class="card-body">
        <img src="{{project.image.url}}" alt="{{project.title}}" class="card-img-top" >

        <h2  >{{project.title}}</h2>
          <p  >{{project.description}}</p>

          
          {% if project.url %}
          <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="_blank">Visit the Project</a>
          {% endif %} 
          
      </div>
    </div>
  </div>
  {%endfor%}
</div>



{%endblock%}

portfolio/templates/layour.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django portfolio </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"  crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css'%}">
</head>
<body class="text-light">
    <!-- este nos ayuda a incluye otras estructura de  html -->
    {% include 'partials/navbar.html'%}
   
    <div class="container p-4">
        {% block content %}
        {% endblock %}
    </div> 
 
</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">DH</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href=" {% url 'blog:posts' %}">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'portfolio/cv.pdf' %}" target="_blank">Download CV</a>
          </li> 
        </ul>
      </div>
    </div>
  </nav>